//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNCDF.CMS {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNCDF.CMS.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The {0} approve was wrong.
        /// </summary>
        public static string ApproveError {
            get {
                return ResourceManager.GetString("ApproveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Approve of {0} was successful..
        /// </summary>
        public static string ApproveSuccess {
            get {
                return ResourceManager.GetString("ApproveSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while trying to delete the record.
        /// </summary>
        public static string ControllerDeleteExceptionMessage {
            get {
                return ResourceManager.GetString("ControllerDeleteExceptionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while trying to retrieve information from {0}.
        /// </summary>
        public static string ControllerGetExceptionMessage {
            get {
                return ResourceManager.GetString("ControllerGetExceptionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to generate a new key from {0}.
        /// </summary>
        public static string GenerateConfirm {
            get {
                return ResourceManager.GetString("GenerateConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a (Total {0} records retrieved).
        /// </summary>
        public static string GridRowCountInfo {
            get {
                return ResourceManager.GetString("GridRowCountInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while loading the page.
        /// </summary>
        public static string PartialViewLoadError {
            get {
                return ResourceManager.GetString("PartialViewLoadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete the record {0}.
        /// </summary>
        public static string RowDeleteConfirm {
            get {
                return ResourceManager.GetString("RowDeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Record successfully removed.
        /// </summary>
        public static string RowDeleteOK {
            get {
                return ResourceManager.GetString("RowDeleteOK", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a {0} is inactive..
        /// </summary>
        public static string RowInactivo {
            get {
                return ResourceManager.GetString("RowInactivo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to record the information {0}.
        /// </summary>
        public static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The {0} registration was wrong.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Registration of {0} was successful..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The {0} update was wrong.
        /// </summary>
        public static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The {0} update was wrong.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Update of {0} was successful..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
